apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-oauth
  namespace: tareas-namespace

spec:
  selector:
    matchLabels:
      app: api-oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: api-oauth
    spec:
      
      containers:
        - name: api-oauth
          image: loliconario69/laravel:v2
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configuracion-de-oauth
          volumeMounts:
            - mountPath: /app
              name: proyecto
      volumes:
        - name: proyecto
          hostPath: 
            path: /root/API-Oauth
            type: Directory

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-oauth
  namespace: tareas-namespace
spec:
  selector:
    matchLabels:
      app: mysql-oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-oauth
    spec:
      containers:
        - name: mysql-oauth
          image: mysql:8
          ports:
            - containerPort: 3306
              name: web
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: oauth