apiVersion: v1
kind: Service
metadata:
  name: api-oauth
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    app: api-oauth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30302
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-oauth
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    app: mysql-oauth
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30202
